runtime: python312

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:
# Serve all static files with fallback to index.html for SPA routing
- url: /assets
  static_dir: dist/assets
  secure: always
  http_headers:
    Cache-Control: 'no-cache, no-store, must-revalidate'
    Pragma: 'no-cache'
    Expires: '0'

- url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))$
  static_files: dist/\1
  upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$
  secure: always
  http_headers:
    Cache-Control: 'no-cache, no-store, must-revalidate'
    Pragma: 'no-cache'
    Expires: '0'

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Cache-Control: 'no-cache, no-store, must-revalidate'
    Pragma: 'no-cache'
    Expires: '0'

