service: api

runtime: nodejs20

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

# Include environment variables from .env.yaml
includes:
  - .env.yaml

# Cloud SQL connection
beta_settings:
  cloud_sql_instances: mobiuschatgpt:us-central1:financialmanager-db

handlers:
- url: /.*
  script: auto
  secure: always

